import { randomUUID } from "node:crypto";
import { Pool } from "pg";
import { config } from "./config";
import { contentBriefSchema, contentSeriesSchema, contentStrategySchema, type ContentBrief, type ContentBriefContext, type ContentBriefInput, type ContentSeries, type ContentSeriesInput, type ContentStrategy, type ContentStrategyInput, type BriefStatus, type StrategyStatus } from "../shared/contracts";

export interface ContentPlanningStore {
  listStrategies(): Promise<ContentStrategy[]>;
  createStrategy(input: ContentStrategyInput): Promise<ContentStrategy>;
  updateStrategy(id: string, values: Partial<Pick<ContentStrategy, "name" | "goal" | "audience" | "tone" | "contentPillars" | "avoidTopics" | "status">>): Promise<ContentStrategy | undefined>;
  listSeries(strategyId: string): Promise<ContentSeries[]>;
  createSeries(strategyId: string, input: ContentSeriesInput): Promise<ContentSeries>;
  updateSeries(id: string, values: Partial<Pick<ContentSeries, "name" | "pillar" | "targetCount" | "status">>): Promise<ContentSeries | undefined>;
  listBriefs(seriesId: string): Promise<ContentBrief[]>;
  createBrief(seriesId: string, input: ContentBriefInput): Promise<ContentBrief>;
  updateBrief(id: string, values: Partial<Pick<ContentBrief, "titleDirection" | "coreQuestion" | "angle" | "summary" | "mustCover" | "mustAvoid" | "noveltyRequirement" | "status">>): Promise<ContentBrief | undefined>;
  getNextContext(): Promise<ContentBriefContext | undefined>;
  getBriefContext(id: string): Promise<ContentBriefContext | undefined>;
}

const now = () => new Date().toISOString();

export class MemoryContentPlanningStore implements ContentPlanningStore {
  private strategies = new Map<string, ContentStrategy>();
  private series = new Map<string, ContentSeries>();
  private briefs = new Map<string, ContentBrief>();
  async listStrategies() { return [...this.strategies.values()].sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
  async createStrategy(input: ContentStrategyInput) { const parsed = contentStrategySchema.parse(input); const item: ContentStrategy = { id: randomUUID(), ...parsed, status: "active", createdAt: now(), updatedAt: now() }; this.strategies.set(item.id, item); return item; }
  async updateStrategy(id: string, values: Partial<Pick<ContentStrategy, "name" | "goal" | "audience" | "tone" | "contentPillars" | "avoidTopics" | "status">>) { const item = this.strategies.get(id); if (!item) return undefined; const updated = { ...item, ...values, updatedAt: now() }; this.strategies.set(id, updated); return updated; }
  async listSeries(strategyId: string) { return [...this.series.values()].filter((item) => item.strategyId === strategyId).sort((a, b) => a.sequence - b.sequence); }
  async createSeries(strategyId: string, input: ContentSeriesInput) { if (!this.strategies.has(strategyId)) throw new Error("内容战略不存在"); const parsed = contentSeriesSchema.parse(input); if ([...this.series.values()].some((item) => item.strategyId === strategyId && item.sequence === parsed.sequence)) throw new Error("同一战略的系列序号已存在"); const item: ContentSeries = { id: randomUUID(), strategyId, ...parsed, status: "active", createdAt: now(), updatedAt: now() }; this.series.set(item.id, item); return item; }
  async updateSeries(id: string, values: Partial<Pick<ContentSeries, "name" | "pillar" | "targetCount" | "status">>) { const item = this.series.get(id); if (!item) return undefined; const updated = { ...item, ...values, updatedAt: now() }; this.series.set(id, updated); return updated; }
  async listBriefs(seriesId: string) { return [...this.briefs.values()].filter((item) => item.seriesId === seriesId).sort((a, b) => a.sequence - b.sequence); }
  async createBrief(seriesId: string, input: ContentBriefInput) { if (!this.series.has(seriesId)) throw new Error("内容系列不存在"); const parsed = contentBriefSchema.parse(input); if ([...this.briefs.values()].some((item) => item.seriesId === seriesId && item.sequence === parsed.sequence)) throw new Error("同一系列的序号已存在"); const item: ContentBrief = { id: randomUUID(), seriesId, ...parsed, status: "planned", createdAt: now(), updatedAt: now() }; this.briefs.set(item.id, item); return item; }
  async updateBrief(id: string, values: Partial<Pick<ContentBrief, "titleDirection" | "coreQuestion" | "angle" | "summary" | "mustCover" | "mustAvoid" | "noveltyRequirement" | "status">>) { const item = this.briefs.get(id); if (!item) return undefined; const updated = { ...item, ...values, updatedAt: now() }; this.briefs.set(id, updated); return updated; }
  private context(brief: ContentBrief): ContentBriefContext | undefined { const series = this.series.get(brief.seriesId); const strategy = series ? this.strategies.get(series.strategyId) : undefined; return strategy && series ? { strategy, series, brief, relatedArticles: [] } : undefined; }
  async getNextContext() { const candidates = [...this.briefs.values()].filter((brief) => brief.status === "planned").map((brief) => this.context(brief)).filter((context): context is ContentBriefContext => Boolean(context && context.strategy.status === "active" && context.series.status === "active")).sort((a, b) => a.series.sequence - b.series.sequence || a.brief.sequence - b.brief.sequence); return candidates[0]; }
  async getBriefContext(id: string) { const brief = this.briefs.get(id); return brief ? this.context(brief) : undefined; }
}

class PgContentPlanningStore implements ContentPlanningStore {
  constructor(private readonly pool: Pool) {}
  async listStrategies() { const r = await this.pool.query<ContentStrategy>("SELECT id, name, goal, audience, tone, content_pillars AS \"contentPillars\", avoid_topics AS \"avoidTopics\", status, created_at AS \"createdAt\", updated_at AS \"updatedAt\" FROM content_strategies ORDER BY created_at DESC"); return r.rows; }
  async createStrategy(input: ContentStrategyInput) { const p = contentStrategySchema.parse(input); const id = randomUUID(); const r = await this.pool.query<ContentStrategy>("INSERT INTO content_strategies (id,name,goal,audience,tone,content_pillars,avoid_topics) VALUES ($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb) RETURNING id,name,goal,audience,tone,content_pillars AS \"contentPillars\",avoid_topics AS \"avoidTopics\",status,created_at AS \"createdAt\",updated_at AS \"updatedAt\"", [id,p.name,p.goal,p.audience??null,p.tone??null,JSON.stringify(p.contentPillars),JSON.stringify(p.avoidTopics)]); return r.rows[0]; }
  async updateStrategy(id: string, values: Partial<Pick<ContentStrategy, "name" | "goal" | "audience" | "tone" | "contentPillars" | "avoidTopics" | "status">>) { const item = await this.getStrategy(id); if (!item) return undefined; const next = { ...item, ...values }; const r = await this.pool.query<ContentStrategy>("UPDATE content_strategies SET name=$2, goal=$3, audience=$4, tone=$5, content_pillars=$6::jsonb, avoid_topics=$7::jsonb, status=$8, updated_at=now() WHERE id=$1 RETURNING id,name,goal,audience,tone,content_pillars AS \"contentPillars\",avoid_topics AS \"avoidTopics\",status,created_at AS \"createdAt\",updated_at AS \"updatedAt\"", [id,next.name,next.goal,next.audience??null,next.tone??null,JSON.stringify(next.contentPillars),JSON.stringify(next.avoidTopics),next.status]); return r.rows[0]; }
  private async getStrategy(id: string) { const r = await this.pool.query<ContentStrategy>("SELECT id,name,goal,audience,tone,content_pillars AS \"contentPillars\",avoid_topics AS \"avoidTopics\",status,created_at AS \"createdAt\",updated_at AS \"updatedAt\" FROM content_strategies WHERE id=$1", [id]); return r.rows[0]; }
  async listSeries(strategyId: string) { const r = await this.pool.query<ContentSeries>("SELECT id,strategy_id AS \"strategyId\",sequence,name,pillar,target_count AS \"targetCount\",order_mode AS \"orderMode\",status,created_at AS \"createdAt\",updated_at AS \"updatedAt\" FROM content_series WHERE strategy_id=$1 ORDER BY sequence", [strategyId]); return r.rows; }
  async createSeries(strategyId: string, input: ContentSeriesInput) { const p = contentSeriesSchema.parse(input); const r = await this.pool.query<ContentSeries>("INSERT INTO content_series (id,strategy_id,sequence,name,pillar,target_count,order_mode) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id,strategy_id AS \"strategyId\",sequence,name,pillar,target_count AS \"targetCount\",order_mode AS \"orderMode\",status,created_at AS \"createdAt\",updated_at AS \"updatedAt\"", [randomUUID(),strategyId,p.sequence,p.name,p.pillar??null,p.targetCount,p.orderMode]); return r.rows[0]; }
  async updateSeries(id: string, values: Partial<Pick<ContentSeries, "name" | "pillar" | "targetCount" | "status">>) { const r = await this.pool.query<ContentSeries>("UPDATE content_series SET name=COALESCE($2,name),pillar=COALESCE($3,pillar),target_count=COALESCE($4,target_count),status=COALESCE($5,status),updated_at=now() WHERE id=$1 RETURNING id,strategy_id AS \"strategyId\",sequence,name,pillar,target_count AS \"targetCount\",order_mode AS \"orderMode\",status,created_at AS \"createdAt\",updated_at AS \"updatedAt\"", [id,values.name??null,values.pillar??null,values.targetCount??null,values.status??null]); return r.rows[0]; }
  async listBriefs(seriesId: string) { const r = await this.pool.query<ContentBrief>("SELECT id,series_id AS \"seriesId\",sequence,title_direction AS \"titleDirection\",core_question AS \"coreQuestion\",angle,summary,must_cover AS \"mustCover\",must_avoid AS \"mustAvoid\",novelty_requirement AS \"noveltyRequirement\",status,created_at AS \"createdAt\",updated_at AS \"updatedAt\" FROM content_briefs WHERE series_id=$1 ORDER BY sequence", [seriesId]); return r.rows; }
  async createBrief(seriesId: string, input: ContentBriefInput) { const p = contentBriefSchema.parse(input); const r = await this.pool.query<ContentBrief>("INSERT INTO content_briefs (id,series_id,sequence,title_direction,core_question,angle,summary,must_cover,must_avoid,novelty_requirement) VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9::jsonb,$10) RETURNING id,series_id AS \"seriesId\",sequence,title_direction AS \"titleDirection\",core_question AS \"coreQuestion\",angle,summary,must_cover AS \"mustCover\",must_avoid AS \"mustAvoid\",novelty_requirement AS \"noveltyRequirement\",status,created_at AS \"createdAt\",updated_at AS \"updatedAt\"", [randomUUID(),seriesId,p.sequence,p.titleDirection,p.coreQuestion??null,p.angle??null,p.summary??null,JSON.stringify(p.mustCover),JSON.stringify(p.mustAvoid),p.noveltyRequirement??null]); return r.rows[0]; }
  async updateBrief(id: string, values: Partial<Pick<ContentBrief, "titleDirection" | "coreQuestion" | "angle" | "summary" | "mustCover" | "mustAvoid" | "noveltyRequirement" | "status">>) { const r = await this.pool.query<ContentBrief>("UPDATE content_briefs SET title_direction=COALESCE($2,title_direction),core_question=COALESCE($3,core_question),angle=COALESCE($4,angle),summary=COALESCE($5,summary),must_cover=COALESCE($6::jsonb,must_cover),must_avoid=COALESCE($7::jsonb,must_avoid),novelty_requirement=COALESCE($8,novelty_requirement),status=COALESCE($9,status),updated_at=now() WHERE id=$1 RETURNING id,series_id AS \"seriesId\",sequence,title_direction AS \"titleDirection\",core_question AS \"coreQuestion\",angle,summary,must_cover AS \"mustCover\",must_avoid AS \"mustAvoid\",novelty_requirement AS \"noveltyRequirement\",status,created_at AS \"createdAt\",updated_at AS \"updatedAt\"", [id,values.titleDirection??null,values.coreQuestion??null,values.angle??null,values.summary??null,values.mustCover?JSON.stringify(values.mustCover):null,values.mustAvoid?JSON.stringify(values.mustAvoid):null,values.noveltyRequirement??null,values.status??null]); return r.rows[0]; }
  async getNextContext() { const r = await this.pool.query("SELECT b.id AS brief_id FROM content_briefs b JOIN content_series s ON s.id=b.series_id JOIN content_strategies t ON t.id=s.strategy_id WHERE b.status='planned' AND s.status='active' AND t.status='active' ORDER BY s.sequence,b.sequence LIMIT 1"); return r.rows[0] ? this.getBriefContext(r.rows[0].brief_id) : undefined; }
  async getBriefContext(id: string) { const r = await this.pool.query("SELECT t.id AS strategy_id,t.name AS strategy_name,t.goal AS strategy_goal,t.audience AS strategy_audience,t.tone AS strategy_tone,t.content_pillars,t.avoid_topics,t.status AS strategy_status,t.created_at AS strategy_created_at,t.updated_at AS strategy_updated_at,s.id AS series_id,s.sequence AS series_sequence,s.name AS series_name,s.pillar,s.target_count,s.order_mode,s.status AS series_status,s.created_at AS series_created_at,s.updated_at AS series_updated_at,b.id AS brief_id,b.sequence,b.title_direction,b.core_question,b.angle,b.summary,b.must_cover,b.must_avoid,b.novelty_requirement,b.status AS brief_status,b.created_at AS brief_created_at,b.updated_at AS brief_updated_at FROM content_briefs b JOIN content_series s ON s.id=b.series_id JOIN content_strategies t ON t.id=s.strategy_id WHERE b.id=$1", [id]); const row = r.rows[0]; if (!row) return undefined; return { strategy: { id: row.strategy_id, name: row.strategy_name, goal: row.strategy_goal, audience: row.strategy_audience, tone: row.strategy_tone, contentPillars: row.content_pillars, avoidTopics: row.avoid_topics, status: row.strategy_status, createdAt: row.strategy_created_at, updatedAt: row.strategy_updated_at }, series: { id: row.series_id, strategyId: row.strategy_id, sequence: row.series_sequence, name: row.series_name, pillar: row.pillar, targetCount: row.target_count, orderMode: row.order_mode, status: row.series_status, createdAt: row.series_created_at, updatedAt: row.series_updated_at }, brief: { id: row.brief_id, seriesId: row.series_id, sequence: row.sequence, titleDirection: row.title_direction, coreQuestion: row.core_question, angle: row.angle, summary: row.summary, mustCover: row.must_cover, mustAvoid: row.must_avoid, noveltyRequirement: row.novelty_requirement, status: row.brief_status, createdAt: row.brief_created_at, updatedAt: row.brief_updated_at } } as ContentBriefContext; }
}

const pool = config.DATABASE_URL ? new Pool({ connectionString: config.DATABASE_URL }) : undefined;
export const contentPlanningStore: ContentPlanningStore = pool ? new PgContentPlanningStore(pool) : new MemoryContentPlanningStore();
