import { useEffect, useRef, useState } from "react";
import { Copy, ImagePlus, RefreshCw, Archive, Trash2 } from "lucide-react";
import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../../components/ui/card";
import { Input } from "../../components/ui/input";
import { mediaApi } from "../../lib/api/media";
import type { MediaAsset } from "../../lib/api/types";
import { copyText } from "../../lib/clipboard";

export function MediaLibraryPage() {
  const [assets, setAssets] = useState<MediaAsset[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState(""); const inputRef = useRef<HTMLInputElement>(null);
  const load = () => { setLoading(true); const params = query ? `?q=${encodeURIComponent(query)}` : ""; mediaApi.list(params).then((result) => setAssets(result.data)).catch(() => setNotice("加载素材失败")).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, [query]);
  const upload = (file?: File) => { if (!file) return; mediaApi.upload(file).then(() => { setNotice("素材已上传"); load(); }).catch((error: unknown) => setNotice(error instanceof Error ? error.message : "上传素材失败")); };
  const copyUrl = (asset: MediaAsset) => copyText(asset.url).then(() => setNotice("素材 URL 已复制")).catch(() => setNotice("复制失败，请手动复制"));
  const archive = (asset: MediaAsset) => mediaApi.remove(asset.id).then(() => { setNotice("素材已归档"); load(); }).catch(() => setNotice("归档素材失败"));
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-muted-foreground">MEDIA LIBRARY</p><h2 className="mt-2 text-3xl font-bold tracking-tight">素材库</h2><p className="mt-2 text-sm text-muted-foreground">集中保存和复用公众号封面、配图等图片素材。</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={load}><RefreshCw size={15} />刷新</Button><Button size="sm" onClick={() => inputRef.current?.click()}><ImagePlus size={15} />上传图片</Button><input ref={inputRef} className="hidden" type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={(event) => { upload(event.target.files?.[0]); event.currentTarget.value = ""; }} /></div></div><Card><CardHeader><CardTitle>图片素材</CardTitle><CardDescription>支持 JPG、PNG、WebP、GIF，单张最大 10 MB。</CardDescription><Input className="mt-3 max-w-sm" placeholder="搜索文件名或标签" value={query} onChange={(event) => setQuery(event.target.value)} /></CardHeader><CardContent>{loading ? <div className="py-12 text-center text-sm text-muted-foreground">正在加载素材…</div> : assets.length === 0 ? <div className="py-12 text-center text-sm text-muted-foreground">暂无图片素材，先上传一张通用封面吧。</div> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{assets.map((asset) => <article className="overflow-hidden rounded-xl border border-border bg-card" key={asset.id}><div className="aspect-[4/3] bg-muted"><img src={asset.url} alt={asset.alt || asset.originalName} className="h-full w-full object-cover" /></div><div className="space-y-3 p-3"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="truncate text-sm font-medium">{asset.originalName}</p><p className="mt-1 text-xs text-muted-foreground">{Math.ceil(asset.sizeBytes / 1024)} KB {asset.width && asset.height ? `· ${asset.width}×${asset.height}` : ""}</p></div><Badge variant={asset.status === "active" ? "secondary" : "outline"}>{asset.status === "active" ? "可用" : "已归档"}</Badge></div>{asset.tags.length > 0 && <div className="flex flex-wrap gap-1">{asset.tags.map((tag) => <Badge variant="outline" key={tag}>{tag}</Badge>)}</div>}<div className="flex gap-2"><Button variant="outline" size="sm" className="flex-1" onClick={() => copyUrl(asset)}><Copy size={14} />复制 URL</Button>{asset.status === "active" && <Button variant="ghost" size="sm" onClick={() => archive(asset)} aria-label="归档素材"><Archive size={14} /></Button>}<Button variant="ghost" size="sm" onClick={() => mediaApi.remove(asset.id).then(() => { setNotice("素材已归档"); load(); }).catch(() => setNotice("归档素材失败"))} aria-label="删除素材"><Trash2 size={14} /></Button></div></div></article>)}</div>}{notice && <p className="mt-4 rounded-md bg-muted p-3 text-sm text-muted-foreground">{notice}</p>}</CardContent></Card></div>;
}
