import { useEffect, useState } from "react";
import { Alert, Button, Card, Empty, Input, Space, Spin, Tag, Typography, Upload } from "antd";
import { Copy, ImagePlus, RefreshCw, Archive, Trash2 } from "lucide-react";
import { mediaApi } from "../../lib/api/media";
import type { MediaAsset } from "../../lib/api/types";
import { copyText } from "../../lib/clipboard";

export function MediaLibraryPage() {
  const [assets, setAssets] = useState<MediaAsset[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState("");
  const load = () => { setLoading(true); const params = query ? `?q=${encodeURIComponent(query)}` : ""; mediaApi.list(params).then((result) => setAssets(result.data)).catch(() => setNotice("加载素材失败")).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, [query]);
  const upload = (file?: File) => { if (!file) return; mediaApi.upload(file).then(() => { setNotice("素材已上传"); load(); }).catch((error: unknown) => setNotice(error instanceof Error ? error.message : "上传素材失败")); };
  const copyUrl = (asset: MediaAsset) => copyText(asset.url).then(() => setNotice("素材 URL 已复制")).catch(() => setNotice("复制失败，请手动复制"));
  const archive = (asset: MediaAsset) => mediaApi.remove(asset.id).then(() => { setNotice("素材已归档"); load(); }).catch(() => setNotice("归档素材失败"));
  return <div className="app-page"><div className="app-page-header"><div><Typography.Text className="app-eyebrow">MEDIA LIBRARY</Typography.Text><Typography.Title level={2} className="app-page-title">素材库</Typography.Title><Typography.Paragraph className="app-page-description">集中保存和复用公众号封面、配图等图片素材。</Typography.Paragraph></div><Space><Button icon={<RefreshCw size={15} />} onClick={load}>刷新</Button><Upload beforeUpload={(file) => { upload(file); return false; }} showUploadList={false} accept="image/jpeg,image/png,image/webp,image/gif"><Button type="primary" icon={<ImagePlus size={15} />}>上传图片</Button></Upload></Space></div><Card className="app-panel-card" title="图片素材" extra={<Input placeholder="搜索文件名或标签" value={query} onChange={(event) => setQuery(event.target.value)} style={{ width: 260 }} />}>{loading ? <div className="app-empty"><Spin /></div> : assets.length === 0 ? <Empty description="暂无图片素材，先上传一张通用封面吧。" /> : <div className="app-media-grid">{assets.map((asset) => <article className="app-media-card" key={asset.id}><div className="app-media-card__image"><img src={asset.url} alt={asset.alt || asset.originalName} /></div><div className="app-media-card__body"><div className="app-media-card__header"><div><p className="app-media-card__name">{asset.originalName}</p><p className="app-media-card__meta">{Math.ceil(asset.sizeBytes / 1024)} KB {asset.width && asset.height ? `· ${asset.width}×${asset.height}` : ""}</p></div><Tag color={asset.status === "active" ? "green" : undefined}>{asset.status === "active" ? "可用" : "已归档"}</Tag></div>{asset.tags.length > 0 && <div className="app-media-card__tags">{asset.tags.map((tag) => <Tag key={tag}>{tag}</Tag>)}</div>}<div className="app-media-card__actions"><Button icon={<Copy size={14} />} onClick={() => copyUrl(asset)}>复制 URL</Button>{asset.status === "active" && <Button icon={<Archive size={14} />} onClick={() => archive(asset)} aria-label="归档素材" /> }<Button danger icon={<Trash2 size={14} />} onClick={() => archive(asset)} aria-label="删除素材" /></div></div></article>)}</div>}{notice && <Alert className="app-notice" type="info" showIcon message={notice} />}</Card></div>;
}
