import { useEffect, useState } from "react";
import { Button, Card, Empty, Space, Spin, Statistic, Typography } from "antd";
import { ArrowUpRight } from "lucide-react";
import { articleApi } from "../../lib/api/articles";
import type { Article, Capabilities } from "../../lib/api/types";

function StatCard({ label, value, hint }: { label: string; value: string | number; hint: string }) {
  return <Card className="app-stat-card"><Statistic title={label} value={value} /><Typography.Text type="secondary">{hint}</Typography.Text></Card>;
}

export function DashboardPage({ onOpenArticles }: { onOpenArticles: (articleId?: string) => void }) {
  const [articles, setArticles] = useState<Article[]>([]); const [total, setTotal] = useState(0); const [caps, setCaps] = useState<Capabilities>(); const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; Promise.all([articleApi.list(), articleApi.capabilities()]).then(([list, channel]) => { if (!active) return; setArticles(list.data); setTotal(list.meta.total); setCaps(channel.data); }).catch(() => undefined).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const recent = articles.slice(0, 5);
  return <div className="app-page"><section className="app-hero"><div><Typography.Text className="app-eyebrow">CONTENT OPERATIONS</Typography.Text><Typography.Title level={2}>把内容，变成可持续的资产。</Typography.Title><Typography.Paragraph>从 AI 接入、文章沉淀到微信公众号发布，所有内容都在一个工作台里清晰流转。</Typography.Paragraph></div><Button type="primary" icon={<ArrowUpRight size={17} />} onClick={() => onOpenArticles()}>查看文章</Button></section><div className="app-stats"><StatCard label="文章总数" value={total} hint="当前可见文章" /><StatCard label="微信草稿" value={caps?.draft ? "可用" : "未配置"} hint={caps?.reason ?? "等待检测"} /><StatCard label="发布能力" value={caps?.publish ? "可用" : "按权限"} hint="操作前自动校验" /></div><div className="app-dashboard-grid"><Card className="app-panel-card" title="最近文章" extra={<Button type="link" onClick={() => onOpenArticles()}>全部文章</Button>}>{loading ? <div className="app-empty"><Spin /></div> : recent.length === 0 ? <Empty description="还没有文章，先通过 API 上传一篇吧。" /> : <div className="app-list">{recent.map((article) => <button className="app-list-item" key={article.id} onClick={() => onOpenArticles(article.id)}><div className="app-list-avatar">{article.title.slice(0, 1)}</div><div className="app-list-copy"><h4>{article.title}</h4><span className="app-list-meta">{article.author || "未署名"} · {new Date(article.createdAt).toLocaleDateString("zh-CN")}</span></div><span className="app-status-pill">{article.status}</span></button>)}</div>}</Card><Card className="app-panel-card" title="下一步"><Space direction="vertical" size={16} style={{ width: "100%" }}><Button block onClick={() => onOpenArticles()}><Space style={{ width: "100%", justifyContent: "space-between" }}><span><strong>接入新的文章</strong><Typography.Text type="secondary" style={{ display: "block", marginTop: 4 }}>通过 API 上传并保存内容</Typography.Text></span><ArrowUpRight size={17} /></Space></Button><div className="app-notice"><strong>AI 生成建议</strong><Typography.Text type="secondary" style={{ display: "block", marginTop: 4 }}>先读取已发布文章和内容规划，再生成下一篇，减少重复主题。</Typography.Text></div></Space></Card></div></div>;
}
