import { useEffect, useState } from "react";
import { ArrowUpRight } from "lucide-react";
import { articleApi } from "../../lib/api/articles";
import type { Article, Capabilities } from "../../lib/api/types";
import { eyebrowClass, panelClass, Stat } from "../../components/ui";
import { Button } from "../../components/ui/button";

export function DashboardPage({ onOpenArticles }: { onOpenArticles: (articleId?: string) => void }) {
  const [articles, setArticles] = useState<Article[]>([]); const [total, setTotal] = useState(0); const [caps, setCaps] = useState<Capabilities>(); const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; Promise.all([articleApi.list(), articleApi.capabilities()]).then(([list, channel]) => { if (!active) return; setArticles(list.data); setTotal(list.meta.total); setCaps(channel.data); }).catch(() => undefined).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const onSelect = (article: Article) => onOpenArticles(article.id);
  const recent = articles.slice(0, 5);
  return <div className="space-y-6"><section className="flex min-h-[230px] items-center justify-between overflow-hidden rounded-[24px] bg-[linear-gradient(120deg,#294b40,#1e342d_55%,#162a25)] px-10 py-[34px] text-[#f4faed]"><div><p className={eyebrowClass}>CONTENT OPERATIONS</p><h2 className="my-2.5 max-w-[600px] text-[clamp(28px,4vw,48px)] tracking-[-.065em]">把内容，变成可持续的资产。</h2><p className="m-0 max-w-[560px] text-[#b4c9bb]">从 AI 接入、文章沉淀到微信公众号发布，所有内容都在一个工作台里清晰流转。</p></div><Button className="hidden sm:flex" onClick={() => onOpenArticles()}>查看文章 <ArrowUpRight size={17} /></Button></section><div className="grid grid-cols-3 gap-4 max-[760px]:grid-cols-1"><Stat label="文章总数" value={total} hint="当前可见文章" /><Stat label="微信草稿" value={caps?.draft ? "可用" : "未配置"} hint={caps?.reason ?? "等待检测"} /><Stat label="发布能力" value={caps?.publish ? "可用" : "按权限"} hint="操作前自动校验" /></div><div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><section className={panelClass}><div className="mb-4 flex items-center justify-between"><div><p className={eyebrowClass}>RECENT ARTICLES</p><h3 className="mt-1.5 text-[22px] tracking-[-.04em]">最近文章</h3></div><Button variant="link" size="sm" className="px-0" onClick={() => onOpenArticles()}>全部文章</Button></div>{loading ? <div className="p-[50px_20px] text-center text-[#84918b]">正在加载文章…</div> : recent.length === 0 ? <div className="p-[50px_20px] text-center text-[#84918b]">还没有文章，先通过 API 上传一篇吧。</div> : <div className="grid">{recent.map((article) => <Button variant="ghost" key={article.id} onClick={() => onSelect(article)} className="!flex !h-auto !w-full !items-center !justify-start !rounded-none !border-t !border-[#edf0ea] !py-4 !text-left"><div className="grid size-10 shrink-0 place-items-center rounded-[11px] bg-[#dceec5] font-extrabold text-[#50723e]">{article.title.slice(0, 1)}</div><div className="min-w-0 flex-1"><h4 className="mb-1 truncate text-[15px]">{article.title}</h4><span className="text-[11px] text-[#a0aaa5]">{article.author || "未署名"} · {new Date(article.createdAt).toLocaleDateString("zh-CN")}</span></div><span className="rounded-full bg-[#eef3ed] px-2 py-1 text-[11px] text-[#5e786a]">{article.status}</span></Button>)}</div>}</section><section className={panelClass}><p className={eyebrowClass}>QUICK START</p><h3 className="mb-4 mt-1.5 text-[22px] tracking-[-.04em]">下一步</h3><div className="grid gap-3"><Button variant="outline" className="!flex !h-auto !items-center !justify-between !p-4 !text-left" onClick={() => onOpenArticles()}><span><strong className="block text-[14px]">接入新的文章</strong><small className="mt-1 block text-[12px] text-[#78877f]">通过 API 上传并保存内容</small></span><ArrowUpRight size={17} className="text-[#6e8e57]" /></Button><div className="rounded-xl bg-[#f2f8ec] p-4"><strong className="block text-[14px] text-[#3d5e47]">AI 生成建议</strong><small className="mt-1 block leading-6 text-[12px] text-[#6e806f]">先读取已发布文章和内容规划，再生成下一篇，减少重复主题。</small></div></div></section></div></div>;
}
