import { useEffect, useState } from "react";
import { Button, Card, Empty, Flex, List, Row, Col, Space, Spin, Statistic, Tag, Typography } from "antd";
import { ArrowUpRight } from "lucide-react";
import { articleApi } from "../../lib/api/articles";
import type { Article, Capabilities } from "../../lib/api/types";

function StatCard({ label, value, hint }: { label: string; value: string | number; hint: string }) {
  return <Card><Statistic title={label} value={value} /><Typography.Text type="secondary">{hint}</Typography.Text></Card>;
}

export function DashboardPage({ onOpenArticles }: { onOpenArticles: (articleId?: string) => void }) {
  const [articles, setArticles] = useState<Article[]>([]); const [total, setTotal] = useState(0); const [caps, setCaps] = useState<Capabilities>(); const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; Promise.all([articleApi.list(), articleApi.capabilities()]).then(([list, channel]) => { if (!active) return; setArticles(list.data); setTotal(list.meta.total); setCaps(channel.data); }).catch(() => undefined).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const recent = articles.slice(0, 5);
  return <Space direction="vertical" size={24} style={{ width: "100%" }}><Card><Flex align="center" justify="space-between" gap={24} wrap="wrap"><div><Typography.Text type="secondary">CONTENT OPERATIONS</Typography.Text><Typography.Title level={2}>把内容，变成可持续的资产。</Typography.Title><Typography.Paragraph>从 AI 接入、文章沉淀到微信公众号发布，所有内容都在一个工作台里清晰流转。</Typography.Paragraph></div><Button type="primary" icon={<ArrowUpRight size={17} />} onClick={() => onOpenArticles()}>查看文章</Button></Flex></Card><Row gutter={[16, 16]}><Col xs={24} md={8}><StatCard label="文章总数" value={total} hint="当前可见文章" /></Col><Col xs={24} md={8}><StatCard label="微信草稿" value={caps?.draft ? "可用" : "未配置"} hint={caps?.reason ?? "等待检测"} /></Col><Col xs={24} md={8}><StatCard label="发布能力" value={caps?.publish ? "可用" : "按权限"} hint="操作前自动校验" /></Col></Row><Row gutter={[16, 16]}><Col xs={24} lg={16}><Card title="最近文章" extra={<Button type="link" onClick={() => onOpenArticles()}>全部文章</Button>}>{loading ? <Flex justify="center"><Spin /></Flex> : recent.length === 0 ? <Empty description="还没有文章，先通过 API 上传一篇吧。" /> : <List dataSource={recent} renderItem={(article) => <List.Item actions={[<Tag key="status">{article.status}</Tag>]}><List.Item.Meta avatar={<Typography.Title level={4} style={{ margin: 0 }}>{article.title.slice(0, 1)}</Typography.Title>} title={<Button type="link" onClick={() => onOpenArticles(article.id)}>{article.title}</Button>} description={`${article.author || "未署名"} · ${new Date(article.createdAt).toLocaleDateString("zh-CN")}`} /></List.Item>} />}</Card></Col><Col xs={24} lg={8}><Card title="下一步"><Space direction="vertical" size={16} style={{ width: "100%" }}><Button block onClick={() => onOpenArticles()}><Flex justify="space-between"><span><strong>接入新的文章</strong><Typography.Text type="secondary" style={{ display: "block" }}>通过 API 上传并保存内容</Typography.Text></span><ArrowUpRight size={17} /></Flex></Button><Card size="small" type="inner" title="AI 生成建议">先读取已发布文章和内容规划，再生成下一篇，减少重复主题。</Card></Space></Card></Col></Row></Space>;
}
