import { useEffect, useState } from "react";
import { RefreshCw, Sparkles } from "lucide-react";
import { candidateApi } from "../../lib/api/candidates";
import type { CandidatePool, ContentCandidate } from "../../lib/api/types";
import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../../components/ui/card";

const riskLabel = { low: "低风险", medium: "中风险", high: "高风险", exact: "完全重复" } as const;

export function CandidatePoolPage() {
  const [pool, setPool] = useState<CandidatePool>(); const [candidates, setCandidates] = useState<ContentCandidate[]>([]); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); candidateApi.daily().then((result) => { setPool(result.data.pool); setCandidates(result.data.candidates); }).catch(() => setNotice("加载每日候选池失败")).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  const recheck = () => candidateApi.recheck().then(() => { setNotice("候选池已重新评估"); load(); }).catch(() => setNotice("重新评估失败"));
  const accept = (candidate: ContentCandidate) => candidateApi.accept(candidate.id).then(() => { setNotice(`已接受《${candidate.title}》，文章已保存`); load(); }).catch(() => setNotice("接受候选文章失败"));
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-muted-foreground">DAILY CANDIDATE POOL</p><h2 className="mt-2 text-3xl font-bold tracking-tight">AI 推荐文章</h2><p className="mt-2 text-sm text-muted-foreground">每天维护一组候选文章，发布后自动重新比较和排序。</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={load}><RefreshCw size={15} />刷新</Button><Button size="sm" onClick={recheck}><Sparkles size={15} />重新评估</Button></div></div><Card><CardHeader><CardTitle>{pool?.poolDate ?? "今日"} 候选池</CardTitle><CardDescription>推荐前 3 篇，评分越高代表内容越新颖、结构越完整。</CardDescription></CardHeader><CardContent>{loading ? <div className="py-12 text-center text-sm text-muted-foreground">正在加载候选池…</div> : candidates.length === 0 ? <div className="py-12 text-center text-sm text-muted-foreground">今日还没有候选文章，请让 AI 提交候选内容。</div> : <div className="grid gap-4">{candidates.map((candidate, index) => <article className="rounded-lg border border-border p-4" key={candidate.id}><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-start gap-3"><div className="grid size-8 shrink-0 place-items-center rounded-full bg-primary text-sm font-bold text-primary-foreground">{index + 1}</div><div><h3 className="font-semibold">{candidate.title}</h3><p className="mt-1 text-sm text-muted-foreground">{candidate.summary || candidate.digest || "暂无梗概"}</p></div></div><div className="flex items-center gap-2"><Badge variant={candidate.risk === "low" ? "secondary" : candidate.risk === "exact" || candidate.risk === "high" ? "destructive" : "outline"}>{riskLabel[candidate.risk]}</Badge><Badge variant="outline">评分 {Math.round(candidate.score * 100)}</Badge></div></div><div className="mt-3 flex flex-wrap gap-2 text-xs text-muted-foreground"><span>相似度 {Math.round(candidate.similarity * 100)}%</span><span>·</span><span>{candidate.status === "recommended" ? "推荐" : candidate.status === "accepted" ? "已接受" : candidate.status === "stale" ? "已过时" : "候选"}</span></div>{candidate.warnings.length > 0 && <ul className="mt-3 grid gap-1 text-xs text-amber-700">{candidate.warnings.map((warning) => <li key={warning}>• {warning}</li>)}</ul>}<div className="mt-4 flex justify-end">{candidate.status !== "accepted" && candidate.status !== "stale" && <Button size="sm" onClick={() => accept(candidate)}>接受并保存文章</Button>}</div></article>)}</div>}{notice && <p className="mt-4 rounded-md bg-muted p-3 text-sm text-muted-foreground">{notice}</p>}</CardContent></Card></div>;
}
