import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "../../components/ui/sheet";
import type { ContentCandidate } from "../../lib/api/types";

const riskLabel = { low: "低风险", medium: "中风险", high: "高风险", exact: "完全重复" } as const;

export function CandidatePreview({ candidate, onOpenChange, onAccept }: { candidate?: ContentCandidate; onOpenChange: (open: boolean) => void; onAccept: (candidate: ContentCandidate) => void }) {
  return <Sheet open={Boolean(candidate)} onOpenChange={onOpenChange}><SheetContent side="right" className="w-full overflow-y-auto sm:max-w-2xl"><SheetHeader><SheetTitle>{candidate?.title || "候选文章预览"}</SheetTitle><SheetDescription>查看完整正文、推荐评分和重复风险。</SheetDescription></SheetHeader>{candidate && <div className="space-y-5"><div className="flex flex-wrap gap-2"><Badge variant={candidate.risk === "low" ? "secondary" : candidate.risk === "exact" || candidate.risk === "high" ? "destructive" : "outline"}>{riskLabel[candidate.risk]}</Badge><Badge variant="outline">推荐分 {Math.round(candidate.score * 100)}</Badge><Badge variant="outline">相似度 {Math.round(candidate.similarity * 100)}%</Badge></div>{candidate.summary && <div className="rounded-lg bg-muted p-4 text-sm leading-6"><strong className="block mb-1">文章梗概</strong>{candidate.summary}</div>}<div className="overflow-hidden rounded-lg border border-border"><iframe title="候选文章正文预览" sandbox="" className="block min-h-[520px] w-full border-0" srcDoc={`<!doctype html><html><body style="font-family:system-ui;line-height:1.8;padding:24px;max-width:680px;margin:auto;color:#25352e">${candidate.content}</body></html>`} /></div>{candidate.warnings.length > 0 && <div className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong className="block mb-2">生成警告</strong><ul className="grid gap-1">{candidate.warnings.map((warning) => <li key={warning}>• {warning}</li>)}</ul></div>}<div className="flex justify-end">{candidate.status !== "accepted" && candidate.status !== "stale" && <Button onClick={() => onAccept(candidate)}>接受并保存文章</Button>}</div></div>}</SheetContent></Sheet>;
}
