import { Alert, Button, Drawer, Flex, Space, Tag, Typography } from "antd";
import type { ContentCandidate } from "../../lib/api/types";
import { copyArticleContent } from "../../lib/clipboard";

const riskLabel = { low: "低风险", medium: "中风险", high: "高风险", exact: "完全重复" } as const;
const riskColor = { low: "green", medium: "orange", high: "red", exact: "red" } as const;

export function CandidatePreview({ candidate, onOpenChange, onAccept, onNotice }: { candidate?: ContentCandidate; onOpenChange: (open: boolean) => void; onAccept: (candidate: ContentCandidate) => void; onNotice: (message: string) => void }) {
  const copy = () => candidate && copyArticleContent(candidate.title, candidate.content);
  return <Drawer title={candidate?.title || "候选文章预览"} open={Boolean(candidate)} onClose={() => onOpenChange(false)} width="min(100vw, 672px)"><Space direction="vertical" size="large" style={{ width: "100%" }}>{candidate && <><Typography.Paragraph type="secondary">查看完整正文、推荐评分和重复风险。</Typography.Paragraph><Space wrap><Tag color={riskColor[candidate.risk]}>{riskLabel[candidate.risk]}</Tag><Tag>推荐分 {Math.round(candidate.score * 100)}</Tag><Tag>相似度 {Math.round(candidate.similarity * 100)}%</Tag></Space>{candidate.summary && <Alert type="info" message="文章梗概" description={candidate.summary} /> }<iframe title="候选文章正文预览" sandbox="" style={{ width: "100%", minHeight: 520, border: "1px solid #d9d9d9", borderRadius: 8 }} srcDoc={`<!doctype html><html><body style="font-family:system-ui;line-height:1.8;padding:24px;max-width:680px;margin:auto;color:#25352e">${candidate.content}</body></html>`} />{candidate.warnings.length > 0 && <Alert type="warning" showIcon message="生成警告" description={<ul>{candidate.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul>} />}<Flex justify="flex-end" gap="small"><Button onClick={() => copy()?.then((mode) => { onNotice(mode === "rich" ? "文章内容已复制，可粘贴到微信公众号" : "文章纯文本已复制"); onOpenChange(false); }).catch((error: unknown) => onNotice(error instanceof Error ? error.message : "复制文章失败"))}>复制文章内容</Button>{candidate.status !== "accepted" && candidate.status !== "stale" && <Button type="primary" onClick={() => onAccept(candidate)}>接受并保存文章</Button>}</Flex></>}</Space></Drawer>;
}
