import { useEffect, useState } from "react";
import { Alert, Button, Card, Empty, Space, Spin, Tag, Typography } from "antd";
import { RefreshCw, Sparkles } from "lucide-react";
import { candidateApi } from "../../lib/api/candidates";
import type { CandidatePool, ContentCandidate } from "../../lib/api/types";
import { CandidatePreview } from "./CandidatePreview";

const riskLabel = { low: "低风险", medium: "中风险", high: "高风险", exact: "完全重复" } as const;
const riskColor = { low: "green", medium: "orange", high: "red", exact: "red" } as const;

export function CandidatePoolPage() {
  const [pool, setPool] = useState<CandidatePool>(); const [candidates, setCandidates] = useState<ContentCandidate[]>([]); const [selected, setSelected] = useState<ContentCandidate>(); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); candidateApi.daily().then((result) => { setPool(result.data.pool); setCandidates(result.data.candidates); }).catch(() => setNotice("加载每日候选池失败")).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  const recheck = () => candidateApi.recheck().then(() => { setNotice("候选池已重新评估"); load(); }).catch(() => setNotice("重新评估失败"));
  const accept = (candidate: ContentCandidate) => candidateApi.accept(candidate.id).then(() => { setSelected(undefined); setNotice(`已接受《${candidate.title}》，文章已保存`); load(); }).catch(() => setNotice("接受候选文章失败"));
  return <div className="app-page"><div className="app-page-header"><div><Typography.Text className="app-eyebrow">DAILY CANDIDATE POOL</Typography.Text><Typography.Title level={2} className="app-page-title">AI 推荐文章</Typography.Title><Typography.Paragraph className="app-page-description">每天维护一组候选文章，发布后自动重新比较和排序。</Typography.Paragraph></div><Space><Button icon={<RefreshCw size={15} />} onClick={load}>刷新</Button><Button type="primary" icon={<Sparkles size={15} />} onClick={recheck}>重新评估</Button></Space></div><Card className="app-panel-card" title={`${pool?.poolDate ?? "今日"} 候选池`} extra={<Typography.Text type="secondary">推荐前 3 篇</Typography.Text>}>{loading ? <div className="app-empty"><Spin /></div> : candidates.length === 0 ? <Empty description="今日还没有候选文章，请让 AI 提交候选内容。" /> : <div className="app-candidate-list">{candidates.map((candidate, index) => <article className="app-candidate" key={candidate.id}><div className="app-candidate__top"><button className="app-candidate__trigger" onClick={() => setSelected(candidate)}><div className="app-candidate__rank">{index + 1}</div><div><h3 className="app-candidate__title">{candidate.title}</h3><p className="app-candidate__summary">{candidate.summary || candidate.digest || "暂无梗概"}</p></div></button><div className="app-candidate__badges"><Tag color={riskColor[candidate.risk]}>{riskLabel[candidate.risk]}</Tag><Tag>评分 {Math.round(candidate.score * 100)}</Tag></div></div><div className="app-candidate__meta"><span>相似度 {Math.round(candidate.similarity * 100)}%</span><span>·</span><span>{candidate.status === "recommended" ? "推荐" : candidate.status === "accepted" ? "已接受" : candidate.status === "stale" ? "已过时" : "候选"}</span></div>{candidate.warnings.length > 0 && <div className="app-warning"><strong>生成警告</strong><ul>{candidate.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></div>}<div className="app-candidate__actions"><Button onClick={() => setSelected(candidate)}>预览全文</Button>{candidate.status !== "accepted" && candidate.status !== "stale" && <Button type="primary" onClick={() => accept(candidate)}>接受并保存文章</Button>}</div></article>)}</div>}{notice && <Alert className="app-notice" type="info" showIcon message={notice} />}</Card><CandidatePreview candidate={selected} onOpenChange={(open) => { if (!open) setSelected(undefined); }} onAccept={accept} onNotice={setNotice} /></div>;
}
