import { useEffect, useState } from "react";
import { KeyRound, Plus, TerminalSquare } from "lucide-react";
import { integrationApi } from "../../lib/api/integrations";
import { adminTokenApi } from "../../lib/api/admin-tokens";
import type { AiIntegration, TokenInfo } from "../../lib/api/types";
import { inputClass, primaryClass } from "../../components/ui";

export function ApiCenterPage() {
  const [integration, setIntegration] = useState<AiIntegration>(); const [tokens, setTokens] = useState<TokenInfo[]>([]); const [name, setName] = useState(""); const [kind, setKind] = useState<TokenInfo["kind"]>("ai_read"); const [secret, setSecret] = useState(""); const [notice, setNotice] = useState("");
  const load = () => Promise.all([integrationApi.getAi(), adminTokenApi.list()]).then(([integration, tokenResult]) => { setIntegration(integration.data); setTokens(tokenResult.data); }).catch(() => setNotice("加载 API 信息失败"));
  useEffect(() => { load(); }, []);
  const create = () => adminTokenApi.create(name, kind).then((result) => { setSecret(result.data.secret); setName(""); setNotice("Token 已生成，请立即复制保存"); load(); }).catch(() => setNotice("生成 Token 失败"));
  const revoke = (id: string) => adminTokenApi.revoke(id).then(() => { setNotice("Token 已撤销"); load(); }).catch(() => setNotice("撤销 Token 失败"));
  return <div className="space-y-6"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-brand-strong">DEVELOPER CENTER</p><h2 className="mt-2 text-3xl font-bold tracking-tight text-slate-900">API 中心</h2><p className="mt-2 text-sm text-slate-500">管理 API 地址、接口目录和访问凭证。</p></div><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><TerminalSquare className="text-brand-strong" /><div><div className="text-xs font-semibold uppercase tracking-wider text-slate-400">API BASE URL</div><p className="mt-1 break-all font-mono text-sm text-slate-700">{integration?.baseUrl || "正在加载…"}</p></div></div></section><div className="grid gap-6 xl:grid-cols-[1.3fr_1fr]"><section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-2 border-b border-slate-100 px-5 py-4 text-sm font-semibold text-slate-800"><TerminalSquare size={17} /><span>接口目录</span></div><div className="divide-y divide-slate-100">{integration && Object.entries(integration.endpoints).map(([key, url]) => <div className="flex items-start justify-between gap-4 p-4" key={key}><div><div className="text-sm font-semibold text-slate-800">{key}</div><div className="mt-1 break-all font-mono text-xs text-slate-400">{url}</div></div><span className="text-xs text-brand-strong">接口</span></div>)}</div></section><section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-2 border-b border-slate-100 px-5 py-4 text-sm font-semibold text-slate-800"><KeyRound size={17} /><span>Token 管理</span></div><div className="space-y-4 p-5"><div className="grid gap-2 sm:grid-cols-[1fr_120px_auto]"><input className={inputClass} placeholder="Token 名称" value={name} onChange={(event) => setName(event.target.value)} /><select className={inputClass} value={kind} onChange={(event) => setKind(event.target.value as TokenInfo["kind"])}><option value="ai_read">AI 读取</option><option value="ai_write">AI 写入</option><option value="api">外部 API</option></select><button className={`${primaryClass} inline-flex items-center justify-center gap-1.5`} onClick={create}><Plus size={16} />生成</button></div>{secret && <div className="break-all rounded-lg bg-amber-50 p-3 font-mono text-xs text-amber-800">只显示一次：{secret}</div>}<div className="divide-y divide-slate-100">{tokens.map((token) => <div className="flex items-center justify-between gap-3 py-3" key={token.id}><div><div className="text-sm font-medium text-slate-800">{token.name}</div><div className="text-xs text-slate-400">{token.kind} · {token.prefix}…</div></div>{token.revokedAt ? <span className="text-xs text-slate-400">已撤销</span> : <button className="text-xs font-semibold text-rose-500" onClick={() => revoke(token.id)}>撤销</button>}</div>)}</div>{notice && <div className="rounded-lg bg-slate-50 p-3 text-xs text-slate-500">{notice}</div>}</div></section></div></div>;
}
