import { X } from "lucide-react";
import type { Article, Capabilities } from "../../lib/api/types";
import { eyebrowClass } from "../../components/ui";
import { Button } from "../../components/ui/button";

export function ArticleDrawer({ article, caps, canPublish, onClose, onArchive, onRestore, onDraft, onRetry, onPublish, onNotice }: { article?: Article; caps?: Capabilities; canPublish: boolean; onClose: () => void; onArchive: () => void; onRestore: () => void; onDraft: () => void; onRetry: () => void; onPublish: () => void; onNotice: (message: string) => void }) {
  if (!article) return null;
  return <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/25"><button aria-label="关闭文章详情" className="absolute inset-0 cursor-pointer border-0 bg-transparent" onClick={onClose} /><aside className="relative h-full w-full max-w-2xl overflow-y-auto bg-background p-6 shadow-2xl"><div className="mb-4 flex items-start justify-between gap-4"><div><p className={eyebrowClass}>ARTICLE PREVIEW</p><h3 className="mt-1.5 text-[22px]">{article.title}</h3></div><Button aria-label="关闭文章详情" variant="ghost" size="icon" onClick={onClose}><X size={18} /></Button></div><div className="mb-5 flex flex-wrap gap-2">{article.status === "archived" ? <Button variant="secondary" size="sm" onClick={onRestore}>恢复</Button> : <Button variant="secondary" size="sm" onClick={onArchive}>归档</Button>}{article.status === "sync_failed" && <Button variant="secondary" size="sm" onClick={onRetry}>重试</Button>}{caps?.draft && <Button size="sm" onClick={onDraft}>创建微信草稿</Button>}{canPublish && <Button size="sm" onClick={onPublish}>提交发布</Button>}</div><div className="overflow-hidden rounded-xl border"><iframe title="文章预览" sandbox="" className="block min-h-[520px] w-full border-0" srcDoc={`<!doctype html><html><body style="font-family:system-ui;line-height:1.8;padding:24px;max-width:680px;margin:auto;color:#25352e">${article.content}</body></html>`} /></div><Button variant="link" size="sm" className="mt-3 px-0" onClick={() => { navigator.clipboard?.writeText(article.id); onNotice("文章 ID 已复制"); }}>复制文章 ID</Button></aside></div>;
}
