import { useEffect } from "react";
import { Button, Card, Checkbox, Empty, Input, Select, Space, Spin, Tag, Typography } from "antd";
import type { Article } from "../../lib/api/types";
import { ArticleDrawer } from "./ArticleDrawer";
import { useArticles } from "./useArticles";

function StatCard({ label, value, hint }: { label: string; value: string | number; hint: string }) {
  return <Card className="app-stat-card"><Typography.Text type="secondary">{label}</Typography.Text><Typography.Title level={3} style={{ margin: "8px 0" }}>{value}</Typography.Title><Typography.Text type="secondary">{hint}</Typography.Text></Card>;
}

export function ArticlesPage({ initialArticleId, onInitialArticleOpened }: { initialArticleId?: string; onInitialArticleOpened: () => void }) {
  const model = useArticles();
  const { articles, total, caps, selected, loading, notice, q, status, includeArchived, canPublish, setQ, setStatus, setIncludeArchived, load, selectArticle, archive, restore, createDraft, retry, publish, updateMedia, setNotice, setSelected } = model;
  useEffect(() => { if (!initialArticleId) return; selectArticle({ id: initialArticleId } as Article); onInitialArticleOpened(); }, [initialArticleId, onInitialArticleOpened, selectArticle]);
  return <div className="app-page"><section className="app-hero"><div><Typography.Text className="app-eyebrow">ARTICLE LIBRARY</Typography.Text><Typography.Title level={2}>让内容，始终井然有序。</Typography.Title><Typography.Paragraph>统一接收、保存和管理外部内容，按需连接微信公众号。</Typography.Paragraph></div></section><div className="app-stats"><StatCard label="文章总数" value={total} hint="当前可见文章" /><StatCard label="微信草稿" value={caps?.draft ? "可用" : "未配置"} hint={caps?.reason ?? "等待检测"} /><StatCard label="发布能力" value={caps?.publish ? "可用" : "按权限"} hint="操作前自动校验" /></div><Card className="app-panel-card" title="文章管理" extra={<Space><Checkbox checked={includeArchived} onChange={(event) => setIncludeArchived(event.target.checked)}>查看归档</Checkbox><Button onClick={load}>刷新</Button></Space>}><div className="app-search-row"><Input className="app-grow" placeholder="搜索标题或摘要" value={q} onChange={(event) => setQ(event.target.value)} /><Select style={{ width: 180 }} value={status || undefined} placeholder="全部状态" allowClear onChange={(value) => setStatus(value ?? "")} options={[{ value: "uploaded", label: "已上传" }, { value: "draft_ready", label: "草稿已创建" }, { value: "published", label: "已发布" }, { value: "sync_failed", label: "同步失败" }, { value: "archived", label: "已归档" }]} /></div>{notice && <Typography.Paragraph className="app-notice">{notice}</Typography.Paragraph>}{loading ? <div className="app-empty"><Spin /></div> : articles.length === 0 ? <Empty description="暂无文章" /> : <div className="app-list">{articles.map((article) => <button className={`app-list-item ${selected?.id === article.id ? "app-list-item--selected" : ""}`} key={article.id} onClick={() => selectArticle(article)}><div className="app-list-avatar">{article.title.slice(0, 1)}</div><div className="app-list-copy"><h4>{article.title}</h4><p>{article.digest || "暂无摘要"}</p><span className="app-list-meta">{article.author || "未署名"} · {new Date(article.createdAt).toLocaleString("zh-CN")}</span></div><Tag color="blue">{article.status}</Tag></button>)}</div>}</Card><ArticleDrawer article={selected} caps={caps} canPublish={canPublish} onClose={() => setSelected(undefined)} onArchive={archive} onRestore={restore} onDraft={createDraft} onRetry={retry} onPublish={publish} onMediaSave={updateMedia} onNotice={setNotice} /></div>;
}
