import { useEffect, useState } from "react";
import { Button, Drawer, Empty, Image, Input, Space, Spin, Tag, Typography } from "antd";
import { Copy, X } from "lucide-react";
import type { Article, Capabilities } from "../../lib/api/types";
import { copyArticleContent, copyText } from "../../lib/clipboard";
import { mediaApi } from "../../lib/api/media";
import type { MediaAsset } from "../../lib/api/types";

export function ArticleDrawer({ article, caps, canPublish, onClose, onArchive, onRestore, onDraft, onRetry, onPublish, onMediaSave, onNotice }: { article?: Article; caps?: Capabilities; canPublish: boolean; onClose: () => void; onArchive: () => void; onRestore: () => void; onDraft: () => void; onRetry: () => void; onPublish: () => void; onMediaSave: (coverUrl: string, coverAssetId?: string) => void; onNotice: (message: string) => void }) {
  const [coverUrl, setCoverUrl] = useState(""); const [coverError, setCoverError] = useState(false); const [assetLoadError, setAssetLoadError] = useState(false); const [assets, setAssets] = useState<MediaAsset[]>([]); const [assetPickerOpen, setAssetPickerOpen] = useState(false); const [selectedAssetId, setSelectedAssetId] = useState<string>();
  useEffect(() => { let active = true; const existingUrl = article?.coverUrl ?? article?.images?.[0] ?? ""; setCoverUrl(existingUrl); setSelectedAssetId(article?.coverAssetId); setCoverError(false); setAssetLoadError(false); setAssetPickerOpen(false); if (article?.coverAssetId) mediaApi.get(article.coverAssetId).then((result) => { if (!active) return; if (result.data.status !== "active") { setSelectedAssetId(undefined); setAssetLoadError(!existingUrl); return; } if (!existingUrl) setCoverUrl(result.data.url); }).catch(() => { if (!active) return; setSelectedAssetId(undefined); setAssetLoadError(!existingUrl); }); return () => { active = false; }; }, [article?.coverAssetId, article?.coverUrl, article?.id, article?.images]);
  if (!article) return null;
  const hasCover = Boolean((coverUrl || selectedAssetId) && !assetLoadError);
  const openAssetPicker = () => mediaApi.list().then((result) => { setAssets(result.data); setAssetPickerOpen(true); }).catch(() => onNotice("加载素材库失败"));
  return <Drawer open title="文章预览" closable={false} onClose={onClose} width="min(100vw, 672px)"><div className="app-drawer-content"><div className="app-drawer-header"><div><Typography.Text className="app-eyebrow">ARTICLE PREVIEW</Typography.Text><Typography.Title level={3} className="app-drawer-title">{article.title}</Typography.Title></div><Button aria-label="关闭文章详情" icon={<X size={18} />} onClick={onClose} /></div><div className="app-drawer-actions"><Button onClick={article.status === "archived" ? onRestore : onArchive}>{article.status === "archived" ? "恢复" : "归档"}</Button>{article.status === "sync_failed" && <Button onClick={onRetry}>重试</Button>}{caps?.draft && <Button type="primary" onClick={onDraft}>创建微信草稿</Button>}{canPublish && <Button type="primary" onClick={onPublish}>提交发布</Button>}</div><section className="app-cover-section"><div className="app-cover-section__header"><div><h4>封面图片</h4><p>微信公众号草稿必须提供一张可公网访问的 HTTPS 图片。</p></div>{hasCover && <Tag color="green">已配置</Tag>}</div><div className="app-cover-form"><Input placeholder="https://example.com/cover.jpg" value={coverUrl} onChange={(event) => { setCoverUrl(event.target.value); setSelectedAssetId(undefined); setCoverError(false); setAssetLoadError(false); }} /><Button type="primary" disabled={!coverUrl.trim() || assetLoadError} onClick={() => onMediaSave(coverUrl.trim(), selectedAssetId)}>保存</Button><Button onClick={openAssetPicker}>从素材库选择</Button></div>{assetLoadError && <Typography.Text type="warning">关联素材无法读取，请重新从素材库选择。</Typography.Text>}{assetPickerOpen && <div className="app-asset-grid">{assets.length === 0 ? <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无可用素材" /> : assets.map((asset) => <button type="button" className={`app-asset-choice ${selectedAssetId === asset.id ? "app-asset-choice--selected" : ""}`} key={asset.id} onClick={() => { setSelectedAssetId(asset.id); setCoverUrl(asset.url); setCoverError(false); setAssetLoadError(false); }}><Image preview={false} src={asset.url} alt={asset.alt || asset.originalName} /></button>)}</div>}{coverUrl && (coverError ? <Typography.Text type="warning">封面地址无法加载，请确认图片 URL 可公网访问。</Typography.Text> : <img className="app-cover-preview" src={coverUrl} alt="文章封面预览" onError={() => setCoverError(true)} />)}</section><iframe title="文章预览" sandbox="" className="app-preview-frame" srcDoc={`<!doctype html><html><body style="font-family:system-ui;line-height:1.8;padding:24px;max-width:680px;margin:auto;color:#25352e">${article.content}</body></html>`} /><Space><Button icon={<Copy size={14} />} onClick={() => copyArticleContent(article.title, article.content).then((mode) => onNotice(mode === "rich" ? "文章内容已复制，可粘贴到微信公众号" : "文章纯文本已复制")).catch((error: unknown) => onNotice(error instanceof Error ? error.message : "复制文章失败"))}>复制文章内容</Button><Button type="link" onClick={() => copyText(article.id).then(() => onNotice("文章 ID 已复制")).catch(() => onNotice("复制失败，请手动复制"))}>复制文章 ID</Button></Space></div></Drawer>;
}
