import { useEffect, useState } from "react";
import { Alert, Button, Card, Descriptions, Empty, Flex, Input, List, Modal, Space, Steps, Tag, Typography } from "antd";
import { planningApi } from "../../lib/api/planning";
import type { Brief, Series, Strategy } from "../../lib/api/types";

export function PlanningPage() {
  const [strategies, setStrategies] = useState<Strategy[]>([]); const [series, setSeries] = useState<Series[]>([]); const [briefs, setBriefs] = useState<Brief[]>([]); const [strategyId, setStrategyId] = useState(""); const [seriesId, setSeriesId] = useState(""); const [notice, setNotice] = useState(""); const [name, setName] = useState(""); const [goal, setGoal] = useState(""); const [seriesName, setSeriesName] = useState(""); const [briefTitle, setBriefTitle] = useState(""); const [detail, setDetail] = useState<Strategy | Series | Brief>(); const [editing, setEditing] = useState<Strategy | Series | Brief>(); const [editName, setEditName] = useState(""); const [editGoal, setEditGoal] = useState(""); const [editTitle, setEditTitle] = useState("");
  useEffect(() => { planningApi.listStrategies().then((result) => { setStrategies(result.data); if (result.data[0]) setStrategyId(result.data[0].id); }).catch(() => setNotice("加载内容战略失败")); }, []);
  useEffect(() => { if (!strategyId) return; planningApi.listSeries(strategyId).then((result) => { setSeries(result.data); setSeriesId(result.data[0]?.id ?? ""); }).catch(() => setNotice("加载内容系列失败")); }, [strategyId]);
  useEffect(() => { if (!seriesId) return setBriefs([]); planningApi.listBriefs(seriesId).then((result) => setBriefs(result.data)).catch(() => setNotice("加载文章任务失败")); }, [seriesId]);
  const startEdit = (item: Strategy | Series | Brief) => { setEditing(item); if ("goal" in item) { setEditName(item.name); setEditGoal(item.goal); } else if ("targetCount" in item) setEditName(item.name); else setEditTitle(item.titleDirection); };
  const saveEdit = () => { if (!editing) return; const request = "goal" in editing ? planningApi.updateStrategy(editing.id, { name: editName, goal: editGoal }) : "targetCount" in editing ? planningApi.updateSeries(editing.id, { name: editName }) : planningApi.updateBrief(editing.id, { titleDirection: editTitle }); request.then(() => { setEditing(undefined); setNotice("内容已更新"); if ("goal" in editing) return planningApi.listStrategies().then((result) => setStrategies(result.data)); if ("targetCount" in editing && strategyId) return planningApi.listSeries(strategyId).then((result) => setSeries(result.data)); if (seriesId) return planningApi.listBriefs(seriesId).then((result) => setBriefs(result.data)); }).catch(() => setNotice("更新失败")); };
  const currentStep = seriesId ? 2 : strategyId ? 1 : 0;
  return (
    <Space direction="vertical" size={24} style={{ width: "100%" }}>
      <Flex align="flex-end" justify="space-between" wrap="wrap" gap="middle">
        <div><Typography.Text type="secondary">CONTENT PLANNING</Typography.Text><Typography.Title level={2}>内容规划</Typography.Title><Typography.Paragraph type="secondary">按战略、系列、文章任务逐级推进内容生产。</Typography.Paragraph></div>
      </Flex>
      <Card><Steps current={currentStep} items={[{ title: "内容战略", description: strategyId ? "已选择战略" : "先定义内容方向" }, { title: "内容系列", description: strategyId ? (seriesId ? "已选择系列" : "选择或创建系列") : "等待战略" }, { title: "文章任务", description: seriesId ? "创建文章任务" : "等待系列" }]} /></Card>
      <Card title={<Flex justify="space-between"><span>1. 内容战略</span><Tag color={strategyId ? "success" : "processing"}>{strategies.length} 个战略</Tag></Flex>}>
        <Space direction="vertical" size="middle" style={{ width: "100%" }}>
          <Space.Compact block><Input placeholder="战略名称" value={name} onChange={(event) => setName(event.target.value)} /><Button type="primary" onClick={() => planningApi.createStrategy({ name, goal, contentPillars: [], avoidTopics: [] }).then((result) => { setStrategies((items) => [result.data, ...items]); setStrategyId(result.data.id); setName(""); setGoal(""); setNotice("战略已创建"); }).catch(() => setNotice("创建战略失败"))}>新建战略</Button></Space.Compact>
          <Input.TextArea rows={2} placeholder="战略目标（可选）" value={goal} onChange={(event) => setGoal(event.target.value)} />
          <List bordered size="small" dataSource={strategies} locale={{ emptyText: <Empty description="暂无内容战略" /> }} renderItem={(item) => <List.Item actions={[<Button key="detail" onClick={() => setDetail(item)}>详情</Button>, <Button key="edit" onClick={() => startEdit(item)}>编辑</Button>, <Button key="select" type={strategyId === item.id ? "primary" : "link"} onClick={() => setStrategyId(item.id)}>选择</Button>]}><List.Item.Meta title={item.name} description={item.goal || "未填写目标"} /></List.Item>} />
        </Space>
      </Card>
      <Card title={<Flex justify="space-between"><span>2. 内容系列</span><Tag color={seriesId ? "success" : "default"}>{series.length} 个系列</Tag></Flex>}>
        {strategyId ? <Space direction="vertical" size="middle" style={{ width: "100%" }}><Space.Compact block><Input placeholder="系列名称" value={seriesName} onChange={(event) => setSeriesName(event.target.value)} /><Button type="primary" onClick={() => planningApi.createSeries(strategyId, { sequence: series.length + 1, name: seriesName, targetCount: 1, orderMode: "sequential" }).then((result) => { setSeries((items) => [...items, result.data]); setSeriesId(result.data.id); setSeriesName(""); setNotice("系列已创建"); }).catch(() => setNotice("创建系列失败"))}>新建系列</Button></Space.Compact><List bordered size="small" dataSource={series} locale={{ emptyText: <Empty description="暂无内容系列" /> }} renderItem={(item) => <List.Item actions={[<Button key="detail" onClick={() => setDetail(item)}>详情</Button>, <Button key="edit" onClick={() => startEdit(item)}>编辑</Button>, <Button key="select" type={seriesId === item.id ? "primary" : "link"} onClick={() => setSeriesId(item.id)}>选择</Button>]}><List.Item.Meta title={`#${item.sequence} ${item.name}`} description={`目标 ${item.targetCount} 篇 · ${item.status}`} /></List.Item>} /></Space> : <Empty description="请先选择内容战略" />}
      </Card>
      <Card title={<Flex justify="space-between"><span>3. 文章任务</span><Tag color={briefs.length ? "success" : "default"}>{briefs.length} 个任务</Tag></Flex>}>
        {seriesId ? <Space direction="vertical" size="middle" style={{ width: "100%" }}><Space.Compact block><Input placeholder="标题方向" value={briefTitle} onChange={(event) => setBriefTitle(event.target.value)} /><Button type="primary" onClick={() => planningApi.createBrief(seriesId, { sequence: briefs.length + 1, titleDirection: briefTitle, mustCover: [], mustAvoid: [] }).then((result) => { setBriefs((items) => [...items, result.data]); setBriefTitle(""); setNotice("文章任务已创建"); }).catch(() => setNotice("创建任务失败"))}>新建任务</Button></Space.Compact><List bordered size="small" dataSource={briefs} locale={{ emptyText: <Empty description="暂无文章任务" /> }} renderItem={(item) => <List.Item actions={[<Button key="detail" onClick={() => setDetail(item)}>详情</Button>, <Button key="edit" onClick={() => startEdit(item)}>编辑</Button>]}><List.Item.Meta title={`#${item.sequence} ${item.titleDirection}`} description={<Tag>{item.status}</Tag>} /></List.Item>} /></Space> : <Empty description="请先选择内容系列" />}
      </Card>
      {notice && <Alert type="info" showIcon message={notice} closable onClose={() => setNotice("")} />}
      <Modal title="内容详情" open={Boolean(detail)} onCancel={() => setDetail(undefined)} footer={null}>{detail && <Descriptions bordered column={1} size="small"><Descriptions.Item label="名称">{"name" in detail ? detail.name : detail.titleDirection}</Descriptions.Item><Descriptions.Item label="状态">{detail.status}</Descriptions.Item><Descriptions.Item label="目标/序号">{"targetCount" in detail ? `${detail.targetCount} 篇` : "sequence" in detail ? `第 ${detail.sequence} 项` : "-"}</Descriptions.Item><Descriptions.Item label="说明">{"goal" in detail ? detail.goal : "seriesId" in detail ? `所属系列 ${detail.seriesId}` : `所属战略 ${detail.strategyId}`}</Descriptions.Item></Descriptions>}</Modal>
      <Modal title="编辑内容" open={Boolean(editing)} onCancel={() => setEditing(undefined)} onOk={saveEdit} okText="保存" cancelText="取消">{"goal" in (editing ?? {}) ? <Space direction="vertical" style={{ width: "100%" }}><Input placeholder="战略名称" value={editName} onChange={(event) => setEditName(event.target.value)} /><Input.TextArea rows={3} placeholder="战略目标" value={editGoal} onChange={(event) => setEditGoal(event.target.value)} /></Space> : "targetCount" in (editing ?? {}) ? <Input placeholder="系列名称" value={editName} onChange={(event) => setEditName(event.target.value)} /> : <Input placeholder="标题方向" value={editTitle} onChange={(event) => setEditTitle(event.target.value)} />}</Modal>
    </Space>
  );
}
