import { useEffect, useState } from "react";
import { api, type Article, type Capabilities } from "../lib/api";

export function App() {
  const [loggedIn, setLoggedIn] = useState(false);
  const [setupRequired, setSetupRequired] = useState(false);
  const [checking, setChecking] = useState(true);
  useEffect(() => { api.setupStatus().then((result) => { setSetupRequired(result.data.required); if (!result.data.required) return api.me().then(() => setLoggedIn(true)).catch(() => undefined); }).catch(() => undefined).finally(() => setChecking(false)); }, []);
  if (checking) return <div className="state full-page">正在检查登录状态…</div>;
  if (setupRequired) return <Setup onSuccess={() => { setSetupRequired(false); setLoggedIn(true); }} />;
  if (!loggedIn) return <Login onSuccess={() => setLoggedIn(true)} />;
  return <Dashboard onLogout={() => { api.logout().finally(() => setLoggedIn(false)); }} />;
}

function Dashboard({ onLogout }: { onLogout: () => void }) {
  const [articles, setArticles] = useState<Article[]>([]);
  const [total, setTotal] = useState(0);
  const [capabilities, setCapabilities] = useState<Capabilities>();
  const [selected, setSelected] = useState<Article>();
  const [q, setQ] = useState("");
  const [status, setStatus] = useState("");
  const [includeArchived, setIncludeArchived] = useState(false);
  const [loading, setLoading] = useState(true);
  const [notice, setNotice] = useState("");
  const [draftOperation, setDraftOperation] = useState<{ articleId: string; operationId: string; draftId?: string }>();
  const load = () => {
    setLoading(true);
    const params = new URLSearchParams(); if (q) params.set("q", q); if (status) params.set("status", status); if (includeArchived) params.set("includeArchived", "true");
    Promise.all([api.listArticles(`?${params}`), api.getCapabilities()]).then(([list, caps]) => { setArticles(list.data); setTotal(list.meta.total); setCapabilities(caps.data); }).catch((error: unknown) => setNotice(error instanceof Error ? error.message : "加载失败")).finally(() => setLoading(false));
  };
  useEffect(() => { load(); }, [q, status, includeArchived]);
  const select = (article: Article) => { api.getArticle(article.id).then((result) => setSelected(result.data)); };
  const archive = () => { if (!selected) return; api.archiveArticle(selected.id).then(() => { setNotice("文章已归档"); setSelected(undefined); load(); }); };
  const restore = () => { if (!selected) return; api.restoreArticle(selected.id).then(() => { setNotice("文章已恢复"); setSelected(undefined); load(); }); };
  const retry = () => { if (!selected) return; api.retry(selected.id).then(() => { setNotice("重试任务已提交"); load(); }).catch((error: unknown) => setNotice(error instanceof Error ? error.message : "重试失败")); };
  const createDraft = () => { if (!selected) return; api.createDraft(selected.id).then((result) => { setDraftOperation({ articleId: selected.id, operationId: result.data.id }); setNotice("草稿任务已提交，正在等待微信公众号响应…"); window.setTimeout(() => api.getOperation(result.data.id).then((operation) => { if (operation.data.status === "succeeded") { setDraftOperation({ articleId: selected.id, operationId: result.data.id, draftId: operation.data.externalId }); setNotice(`草稿已创建：${operation.data.externalId ?? result.data.id}`); load(); } else if (operation.data.status === "failed") setNotice(operation.data.errorMessage ?? "创建草稿失败"); }), 1200); }).catch((error: unknown) => setNotice(error instanceof Error ? error.message : "创建草稿失败")); };
  const publishDraft = () => { if (!draftOperation?.draftId) return; api.publish(draftOperation.articleId, draftOperation.draftId).then((result) => setNotice(`发布任务已提交：${result.data.id}`)).catch((error: unknown) => setNotice(error instanceof Error ? error.message : "发布失败")); };

  return <div className="shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">文</span><span>文章中台</span></div><nav><a className="nav-item active">工作台</a><a className="nav-item">文章管理</a><a className="nav-item">渠道设置</a></nav><div className="sidebar-foot">通用渠道架构 · v0.2</div></aside>
    <main className="main"><header className="topbar"><div><p className="eyebrow">CONTENT OPERATIONS</p><h1>工作台</h1></div><div className="profile"><span className="status-dot" /> 系统运行正常 <button className="logout-button" onClick={onLogout}>退出</button></div></header>
      <section className="content"><div className="hero"><div><p className="eyebrow">ARTICLE LIBRARY</p><h2>让内容，始终井然有序。</h2><p>统一接收、保存和管理外部内容，按需连接微信公众号。</p></div><div className="hero-orbit"><span>HTML</span><span>API</span><span>WECHAT</span></div></div>
        <div className="stat-grid"><Stat label="文章总数" value={total} hint="当前可见文章" /><Stat label="微信草稿" value={capabilities?.draft ? "可用" : "未配置"} hint={capabilities?.reason ?? "等待检测"} /><Stat label="发布能力" value={capabilities?.publish ? "可用" : "按权限"} hint="操作前自动校验" /></div>
        <section className="panel"><div className="panel-head"><div><p className="eyebrow">ARTICLE LIBRARY</p><h3>文章管理</h3></div><div className="detail-actions"><label className="archive-toggle"><input type="checkbox" checked={includeArchived} onChange={(event) => setIncludeArchived(event.target.checked)} /> 查看归档</label><button className="button secondary" onClick={load}>刷新</button></div></div><div className="filters"><input aria-label="搜索文章" placeholder="搜索标题或摘要" value={q} onChange={(event) => setQ(event.target.value)} /><select aria-label="筛选状态" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">全部状态</option><option value="uploaded">已上传</option><option value="draft_ready">草稿已创建</option><option value="published">已发布</option><option value="sync_failed">同步失败</option><option value="archived">已归档</option></select></div>{notice && <div className="notice">{notice}</div>}{loading ? <div className="state">正在加载文章…</div> : articles.length === 0 ? <div className="empty"><div className="empty-icon">✦</div><strong>没有匹配文章</strong><p>通过上传 API 发送文章后，它会出现在这里。</p></div> : <div className="article-list">{articles.map((article) => <button className={`article-row ${selected?.id === article.id ? "selected" : ""}`} key={article.id} onClick={() => select(article)}><div className="article-cover">{article.title.slice(0, 1)}</div><div className="article-main"><h4>{article.title}</h4><p>{article.digest || "暂无摘要"}</p><span>{article.author || "未署名"} · {new Date(article.createdAt).toLocaleString("zh-CN")}</span></div><span className={`badge ${article.status}`}>{article.status}</span></button>)}</div>}</section>
        {selected && <ArticleDetail article={selected} capabilities={capabilities} onArchive={archive} onRestore={restore} onRetry={retry} onDraft={createDraft} onPublish={publishDraft} canPublish={Boolean(draftOperation?.draftId)} onNotice={setNotice} />}
      </section></main>
  </div>;
}

function ArticleDetail({ article, capabilities, onArchive, onRestore, onRetry, onDraft, onPublish, canPublish, onNotice }: { article: Article; capabilities?: Capabilities; onArchive: () => void; onRestore: () => void; onRetry: () => void; onDraft: () => void; onPublish: () => void; canPublish: boolean; onNotice: (value: string) => void }) {
  return <section className="detail-panel"><div className="panel-head"><div><p className="eyebrow">ARTICLE PREVIEW</p><h3>{article.title}</h3></div><div className="detail-actions">{article.status === "archived" ? <button className="button secondary" onClick={onRestore}>恢复</button> : <button className="button secondary" onClick={onArchive}>归档</button>}{article.status === "sync_failed" && <button className="button secondary" onClick={onRetry}>重试</button>}{capabilities?.draft && article.status !== "archived" && <button className="button primary" onClick={onDraft}>创建微信草稿</button>}{capabilities?.publish && canPublish && <button className="button primary" onClick={onPublish}>提交发布</button>}</div></div><div className="detail-meta">{article.author || "未署名"} · {new Date(article.createdAt).toLocaleString("zh-CN")} · <span className={`badge ${article.status}`}>{article.status}</span></div><div className="preview-frame"><iframe title="文章预览" sandbox="" srcDoc={`<!doctype html><html><body style="font-family:system-ui;line-height:1.8;padding:24px;max-width:680px;margin:auto;color:#25352e">${article.content}</body></html>`} /></div>{!capabilities?.draft && <p className="muted">{capabilities?.reason ?? "当前渠道未配置"}</p>}<button className="text-button" onClick={() => { navigator.clipboard?.writeText(article.id); onNotice("文章 ID 已复制"); }}>复制文章 ID</button></section>;
}

function Login({ onSuccess }: { onSuccess: () => void }) { const [recovery, setRecovery] = useState(false); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); if (recovery) return <Recovery onSuccess={onSuccess} onBack={() => setRecovery(false)} />; return <div className="login-page"><form className="login-card" onSubmit={(event) => { event.preventDefault(); api.login(username, password).then(onSuccess).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "登录失败")); }}><div className="brand"><span className="brand-mark">文</span><span>文章中台</span></div><p className="eyebrow">ADMIN CONSOLE</p><h1>登录后台</h1><label>用户名<input autoFocus value={username} onChange={(event) => setUsername(event.target.value)} /></label><label>密码<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label>{error && <p className="login-error">{error}</p>}<button className="login-button" type="submit">进入工作台</button><button className="text-button login-link" type="button" onClick={() => setRecovery(true)}>忘记密码？</button></form></div>; }
function Recovery({ onSuccess, onBack }: { onSuccess: () => void; onBack: () => void }) { const [username, setUsername] = useState(""); const [code, setCode] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [error, setError] = useState(""); return <div className="login-page"><form className="login-card" onSubmit={(event) => { event.preventDefault(); if (password !== confirm) { setError("两次密码不一致"); return; } api.resetPassword(username, code, password).then(onSuccess).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "重置失败")); }}><div className="brand"><span className="brand-mark">文</span><span>文章中台</span></div><p className="eyebrow">PASSWORD RECOVERY</p><h1>重置管理员密码</h1><p className="setup-copy">请先在服务器执行恢复码命令，再将一次性恢复码粘贴到这里。</p><label>管理员用户名<input autoFocus value={username} onChange={(event) => setUsername(event.target.value)} /></label><label>一次性恢复码<input value={code} onChange={(event) => setCode(event.target.value)} /></label><label>新密码<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="至少 12 位" /></label><label>确认新密码<input type="password" value={confirm} onChange={(event) => setConfirm(event.target.value)} /></label>{error && <p className="login-error">{error}</p>}<button className="login-button" type="submit">重置并登录</button><button className="text-button login-link" type="button" onClick={onBack}>返回登录</button></form></div>; }
function Setup({ onSuccess }: { onSuccess: () => void }) { const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [error, setError] = useState(""); return <div className="login-page"><form className="login-card" onSubmit={(event) => { event.preventDefault(); if (password !== confirm) { setError("两次密码不一致"); return; } api.initialize(username, password).then(onSuccess).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "初始化失败")); }}><div className="brand"><span className="brand-mark">文</span><span>文章中台</span></div><p className="eyebrow">FIRST RUN SETUP</p><h1>创建管理员</h1><p className="setup-copy">这是首次启动，请先创建唯一的后台管理员账号。初始化完成后不会开放公共注册。</p><label>管理员用户名<input autoFocus value={username} onChange={(event) => setUsername(event.target.value)} placeholder="例如：admin" /></label><label>管理员密码<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="至少 12 位" /></label><label>确认密码<input type="password" value={confirm} onChange={(event) => setConfirm(event.target.value)} /></label>{error && <p className="login-error">{error}</p>}<button className="login-button" type="submit">完成初始化</button></form></div>; }
function Stat({ label, value, hint }: { label: string; value: string | number; hint: string }) { return <div className="stat-card"><span>{label}</span><strong>{value}</strong><small>{hint}</small></div>; }
